Make tool installation more user-friendly
We still support 2 types of installations using `install.bash`:
1. using remote git - a production installation which installs latest
   master branch by default.
2. using local sources - an installation type which is provided for
   development purposes. It is a part of testing procedure also.
By default, a tool is installed into ``${HOME}/.elegant-git` directory.
Meanwhile, the installation path can be customized. See `install.bash`
for further details.

Uninstall process is removed from `install.bash` as it has to be
managed separately.

New project layout:
.
├── bin          - production scripts only
├── completions  - completions for different shells
├── docs         - WEB site with documentation
├── libexec      - auxiliary scripts needed for production scripts
└── tests        - unit tests

Also, `run-tests` is working only from a docker environment as it may
install 'bad' code into `/usr/local`.

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -1,4 +1,18 @@
-#!/bin/bash -e
+#!/usr/bin/env bash
+# This script is destructive! That's why it will work only if a specific variable is set.
+# It's recommended to run it within a docker container only.
+set -e
 
-bats --tap src/test
-pdd --source=$(pwd) --verbose --file=/dev/null
+if [[ -z $EG_ENABLE_TESTING ]]; then
+    echo "Testing is disabled!"
+    exit 1
+fi
+
+fail() {
+    echo $@
+    exit 1
+}
+
+bats --tap tests                                  || fail "Unit tests are failed."
+./install.bash /usr/local src && git elegant help || fail "Installation test is failed."
+pdd --source=$(pwd) --verbose --file=/dev/null    || fail "Unreadable todo is identified."
