Run tests on multiple Bash and Git versions
Now Elegant Git is tested on 2 Git and 3 Bash versions (6 environments
in total). All testing happens within Docker containers that work in
parallel. The overall workflow is the following:
1. `workflows` runs a given command
2. the command starts a needed number of containers in parallel, waits
   until they are exited, and reports the status

Such a running scheme allows to run more tests and total duration is
equal to the duration of the longest test execution.

From the technical side, the worker containers don't package the
appropriate workflows scripts, they just configure them by default. This
allows making script changes without rebuilding the images. Also, as
usual, all workers bind the source files in the container's volume and
use them for the execution.

diff --git a/workflows b/workflows
--- a/workflows
+++ b/workflows
@@ -3,43 +3,49 @@ set -e
 
 source ./libexec/plugins/text
 
-bash_3_2_57=3.2.57
+# bash versions
+bash_3_2_57=3.2.57 # MACOS default
+bash_4_4_23=4.4.23
 bash_5_0_17=5.0.17
+# python versions
 python_3_8_3=3.8.3
+# git versions
+git_2_13_7=2.13.7
 git_2_26_2=2.26.2
-bashes=(
-    ${bash_5_0_17}
-    ${bash_3_2_57}
-)
-gits=(
-    ${git_2_26_2}
-)
-base_testing_worker=bash${bash_3_2_57}-git${git_2_26_2}
+
+--worker-tag() {
+    # usege: --worker-tag <bash version> <git version>
+    echo ${1}-${2}
+}
 
 eg_docker_organization=beeshive
-eg_documents_repository=${eg_docker_organization}/elegant-git-docs-workflows
-eg_documents_image=${eg_documents_repository}:python${python_3_8_3}-bash${bash_5_0_17}
+eg_documents_repository=${eg_docker_organization}/elegant-git-docs-worker
+eg_documents_bash=${bash_5_0_17}
+eg_documents_git=${git_2_26_2}
+eg_documents_image=${eg_documents_repository}:$(--worker-tag ${eg_documents_bash} ${eg_documents_git})
 eg_bats_repository=${eg_docker_organization}/elegant-git-bats-worker
-eg_bats_image=${eg_bats_repository}:${base_testing_worker}
-
+bats_worker_tags=(
+    $(--worker-tag ${bash_3_2_57} ${git_2_13_7})
+    $(--worker-tag ${bash_4_4_23} ${git_2_13_7})
+    $(--worker-tag ${bash_5_0_17} ${git_2_13_7})
+    $(--worker-tag ${bash_3_2_57} ${git_2_26_2})
+    $(--worker-tag ${bash_4_4_23} ${git_2_26_2})
+    $(--worker-tag ${bash_5_0_17} ${git_2_26_2})
+)
 
 --publish-worker() {
     info-text "Select image to push:"
-    select tag in $(docker image ls --filter reference=${1} --format "{{.Repository}}:{{.Tag}}"); do
+    select tag in $(docker image ls --filter reference=${1} --format "{{.Repository}}:{{.Tag}}") exit; do
+        if test ${tag} = "exit"; then break; fi
         docker push ${tag}
-        break
     done
 }
 
 # docs workflows
 prepare-docs-worker() {
-    local bashversion=${bash_5_0_17}
-    local pythonversion=${python_3_8_3}
     docker build --tag ${eg_documents_image} \
-                 --label bashversion=${bashversion} \
-                 --label pythonversion=${pythonversion} \
-                 --build-arg bashversion=${bashversion} \
-                 --build-arg pythonversion=${pythonversion} \
+                 --build-arg bashversion=${eg_documents_bash} \
+                 --build-arg gitversion=${eg_documents_git} \
                  --file .workflows/docs/Dockerfile .
 }
 
@@ -68,100 +74,130 @@ serve-docs() {
 # docs workflows
 
 repository() {
-    info-text "Start container..."
-    docker run --interactive --tty --detach --rm \
-               --name repository \
-               --workdir /tmp/elegant-git-repo \
-               --mount type=bind,source=$(pwd),target=/elegant-git \
-               ${eg_bats_image} bash
-    info-text "Init repository..."
-    docker exec --interactive --tty repository bash -c "
-        cd /elegant-git
-        source tests/addons-repo.bash
-        source tests/addons-common.bash
-        repo-new
-    "
-    info-text "Install Elegant Git..."
-    docker exec --interactive --tty repository bash -c "
-        cd /elegant-git
-        .workflows/installation-workflows.bash install
-    "
-    info-text "Ready! Enjoy experiments..."
-    docker attach repository
+    info-text "Select worker:"
+    select worker in ${bats_worker_tags[*]} exit; do
+        if test ${worker} = "exit"; then break; fi
+        info-text "Start container..."
+        docker run --interactive --tty --detach --rm \
+                --name repository \
+                --workdir /tmp/elegant-git-repo \
+                --mount type=bind,source=$(pwd),target=/elegant-git \
+                ${eg_bats_repository}:${worker} bash
+        info-text "Init repository..."
+        docker exec --interactive --tty repository bash -c "
+            cd /elegant-git
+            source tests/addons-repo.bash
+            source tests/addons-common.bash
+            repo-new
+        "
+        info-text "Install Elegant Git..."
+        docker exec --interactive --tty repository bash -c "
+            cd /elegant-git
+            .workflows/installation-workflows.bash install
+        "
+        info-text "Ready! Enjoy experiments..."
+        docker attach repository
+    done
 }
 
 # testing workflows
 prepare-bats-worker() {
-    info-text "Select Bash and Git version:"
-    select bashv in ${bashes[*]}; do
-        bashversion=${bashv}
-        break
-    done
-    select gitv in ${gits[*]}; do
-        gitversion=${gitv}
-        break
-    done
     local batsversion=v1.2.0
-    docker build --tag ${eg_bats_repository}:bash${bashversion}-git${gitversion} \
-                 --label bashversion=${bashversion} \
-                 --label gitversion=${gitversion} \
-                 --label batsversion=${batsversion} \
-                 --build-arg bashversion=${bashversion} \
-                 --build-arg gitversion=${gitversion} \
-                 --build-arg batsversion=${batsversion} \
-                 .workflows/bats
+    info-text "Select worker:"
+    select worker in ${bats_worker_tags[*]} exit; do
+        if test ${worker} = "exit"; then break; fi
+        docker build --tag ${eg_bats_repository}:${worker} \
+                     --build-arg bashversion=${worker%%-*} \
+                     --build-arg gitversion=${worker##*-} \
+                     --build-arg batsversion=${batsversion} \
+                     .workflows/bats
+    done
 }
 
 publish-bats-worker() {
     --publish-worker ${eg_bats_repository}
 }
 
-testing() {
-    echo $@
-    docker run --interactive --rm  \
-               --mount type=bind,source=$(pwd),target=/elegant-git \
-               ${eg_bats_image} some_tests "$@"
+--bats-workers() {
+    # usage: --bats-workers <task-name> [<args> ...]
+    local task=${1}; shift
+    for tag in ${bats_worker_tags[*]}; do
+        docker run --detach \
+                   --mount type=bind,source=$(pwd),target=/elegant-git \
+                   --name elegant-git-${task}-${tag} \
+                   ${eg_bats_repository}:${tag} "${@}"
+    done
 }
 
-__fail() {
-    error-box $@
-    exit 1
+testing() {
+    --bats-workers some-bats some_tests "$@"
+    --report-containerized-jobs
 }
 
 test-commands-docs() {
-    (
-        generate-docs
-        git update-index --really-refresh
-        git diff-index --quiet HEAD docs
-    ) || __fail "'docs/commands.md' is not up to date. Please run './workflows generate-docs' and commit the changes."
+    docker run --detach \
+               --mount type=bind,source=$(pwd),target=/elegant-git \
+               --name elegant-git-test-commands-docs \
+               ${eg_documents_image} ci
 }
 
 test-docs-site() {
-    {
-        docker run --interactive --rm \
-                   --mount type=bind,source=$(pwd),target=/elegant-git \
-                ${eg_documents_image} build
-    } || __fail "Unable to build the documentation site."
+    docker run --detach \
+               --name elegant-git-test-docs-site \
+               --mount type=bind,source=$(pwd),target=/elegant-git \
+               ${eg_documents_image} build
 }
 
 test-installation() {
-    (
-        docker run --interactive --rm \
-               --mount type=bind,source=$(pwd),target=/elegant-git \
-               ${eg_bats_image} bash -c "
+    --bats-workers installation bash -c "
                .workflows/installation-workflows.bash install
                .workflows/installation-workflows.bash smoke-tests
         "
-    ) || __fail "Installation test is failed."
 }
 
 ci() {
-    docker run --interactive --rm \
-               --mount type=bind,source=$(pwd),target=/elegant-git \
-               ${eg_bats_image} all_tests
+    --bats-workers all-bats all_tests
     test-commands-docs
     test-docs-site
     test-installation
+    --report-containerized-jobs
+}
+
+--report-containerized-jobs() {
+    info-box "Waiting for containerized jobs are completed ..."
+    while test -n "$(docker container ls --filter name=elegant-git --format {{.Names}})"; do
+        local containers=($(docker container ls --filter name=elegant-git --format {{.Names}}))
+        info-text "${#containers[*]} jobs still working ..."
+        sleep 3
+    done
+    info-box "Reporting job statuses ..."
+    local passes=($(docker container ls --all --filter exited=0 --format {{.Names}}))
+    for passed in ${passes[*]} ; do
+        info-text "${passed} job is passed."
+    done
+    if test ${#passes[*]} -ne 0 ; then
+        info-text "Remove containers for passed jobs ..."
+        docker container rm -f ${passes[*]}
+    fi
+    local failures=($(docker container ls --all --filter name=elegant-git --format {{.Names}}))
+    for failed in ${failures[*]} ; do
+        error-text "${failed} job is failed."
+        docker logs ${failed}
+    done
+    if test ${#failures[*]} -ne 0 ; then
+        info-text "Remove containers for failed jobs ..."
+        docker container rm -f ${failures[*]}
+    fi
+    if test ${#failures[*]} -ne 0; then
+        error-box "${#passes[*]} jobs are passed and ${#failures[*]} are failed."
+        error-text "Failed jobs:"
+        for fail in ${failures[*]}; do
+            error-text "- ${fail}"
+        done
+        exit 1
+    else
+        info-box "${#passes[*]} jobs are passed."
+    fi
 }
 
 robot() {
@@ -172,6 +208,7 @@ robot() {
     for command_file in ${command_files[@]}; do
         local command_name=$(basename ${command_file})
         if ! test -f tests/${command_name}.bats; then continue; fi
+        info-box "Run tests for ${command_file}"
         ( testing ${command_name} && info-text "'${command_file}' testing is passed." ) || {
             error-text "'${command_name}' testing is failed."
             smart_testing_status=failed
@@ -184,6 +221,7 @@ robot() {
             continue # already tested
         fi
         if ! test -f tests/${file_name}; then continue; fi
+        info-box "Run tests in ${file_name}"
         ( testing ${file_name} && info-text "'${file_name}' testing is passed.") || {
             error-text "'${file_name}' testing is failed."
             smart_testing_status=failed
@@ -210,8 +248,8 @@ Available commands:
     preview-docs         runs a site with the current documentation (http://localhost)
     serve-docs           runs 'generate-docs' and 'preview-docs'
   testing modifications
-    prepare-bats-worker  builds a new '${eg_bats_image}' image
-    publish-bats-worker  pushes the '${eg_bats_image}' image
+    prepare-bats-worker  builds a new '${eg_bats_repository}' image
+    publish-bats-worker  pushes the '${eg_bats_repository}' image
     testing              runs bats tests; accepts a optional pattern for tests
                          filtering ("${BASH_SOURCE[0]} testing work" run all tests
                          which have the word in the test name)
@@ -250,8 +288,9 @@ main() {
     if [[ -z ${command} ]]; then
         question-text "Please select a command:"
         echo ""
-        select any in ${commands[@]}; do
-            command=${any}
+        select choise in ${commands[@]} exit; do
+            if test ${choise} = "exit"; then exit; fi
+            command=${choise}
             if test ${command} = testing; then
                 question-text "Please give the tests pattern: "
                 read args
@@ -263,6 +302,9 @@ main() {
     fi
     info-box "Run:" ${command} ${args:-${@}}
     ${command} ${args:-${@}}
+    if [[ ${command} =~ "test-" ]]; then
+        --report-containerized-jobs
+    fi
 }
 
 main ${@}
